### ISSUE TITLE
schemasheets doesn't seem to instantiate mixins yet

### ISSUE THREAD

**Issue by turbomam** [linkml/schemasheets#32]

**Comment by turbomam** [comment]
> Traceback (most recent call last):
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/bin/sheets2linkml", line 8, in <module>
    sys.exit(convert())
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/schemasheets/schemamaker.py", line 701, in convert
    schema = sm.create_schema(list(tsv_files))
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/schemasheets/schemamaker.py", line 213, in create_schema
    self.merge_sheet(f, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/schemasheets/schemamaker.py", line 276, in merge_sheet
    raise SchemaSheetRowException(f'Error in line {line_num}, row={row}') from e
schemasheets.schemamaker.SchemaSheetRowException: Error in line 5, row={'class': '', 'slot': '', 'description': 'a test mixin', 'mixin': 'test mixin'}

**Comment by turbomam** [comment]
@cmungall kindly reminded me that there's no such thing as a mixin element, only an element with the mixin attribute set to true.
